### ISSUE TITLE
Comparison to djot

### ISSUE THREAD

**Issue by dumblob** [srackham/rimu#5]
I wonder where rimu stands compared to [djot](https://github.com/jgm/djot/ ).

Any insights (features-wise, implementation**s**-wise, etc.)?

**Comment by srackham** [comment]
Thanks for pointing out djot, I hadn't come across it before. It shares most of the same design goals with Rimu, the real differences seem to be:

- Rimu can be extended with macros and has a maleable syntax (replacements, delimited block definitions, quote definitions).

- Rimu implements a subset of Markdown but is less Markdown oriented, aiming to be a better text markup language rather than a better Markdown (AsciiDoc, not Markdown, was my starting point).

- djot is written in Lua; Rimu has been ported to six languages: TypeScript, Kotlin, Go, Dart, Python and recently V.

Implementation-wise, djot uses AST compiler technology which is much nicer than my ad hoc regex based approach -- I really must learn how compilers work :-)

**Comment by dumblob** [comment]
Thanks for a super quick reply - it answers my question :wink:.
